SECRET_KEY : 'randomnumbercp'
URL_HOST : 'https://curugpletuk.fly.dev'
REDIS_URL : 'redis://default:b7f0a29f8def4fce82afe34c5aaa7838@fly-curugpletukredis.upstash.io:6379'
PASSWORD_DB : '8hzkmZYVBjX5eZT'