SECRET_KEY : 'randomnumbercp'
URL_HOST : 'https://curugpletuk.fly.dev'
REDIS_URL : 'redis://default:cef319d49ca1412584b4acc88d27a9b5@fly-curug-pletuk-db.upstash.io:6379'
PASSWORD_DB : 'Ll1ZbzENdBSr8Qk'