# :schedule:
#   session_worker:
#     cron: '0 * * * *'
#     class: SessionWorker


# :concurrency: 5
:scheduler:
  :listened_queues:
    - default
  :schedule:
    session_worker:
      cron: '0 * * * * *'
      class: SessionWorker
      # queue: default
