# :schedule:
#   session_worker:
#     cron: '0 * * * *'
#     class: SessionWorker


# :concurrency: 5
:scheduler:
  :listened_queues:
    - default
  :schedule:
    order_worker:
      cron: '0 * * * * *'   # Runs once per minute
      class: OrderWorker  
    session_worker:
      cron: '0 * * * * *'
      class: SessionWorker
      # queue: default
